"""PDF case-report export using fpdf2 — pure Python, no system-level
Cairo/Pango dependency. Builds an actual laid-out document straight from
the FraudCase (the same inputs ReportGenerator._build_markdown uses),
not a rendering of the markdown report text.

Amounts are written as "Rs." rather than the ₹ glyph: fpdf2's core
Helvetica font is WinAnsi-only and can't encode U+20B9, and embedding a
Unicode TTF just for one symbol isn't worth the extra file/complexity
this close to a deadline.
"""

from __future__ import annotations

from typing import Optional

from fpdf import FPDF
from fpdf.enums import XPos, YPos

from fraudlens.core.privacy import mask_identifier, mask_ip
from fraudlens.models.schemas import AnalystDecision, FraudCase

_BADGES = {
    "clear": "CLEAR",
    "review": "REVIEW",
    "block": "BLOCK",
    "block_and_report": "BLOCK & ESCALATE",
}

_FOREGROUND = (26, 33, 48)
_MUTED = (91, 100, 115)
_BORDER = (223, 228, 236)
_COBALT = (41, 84, 224)
_RISK_HIGH = (194, 59, 34)

_PAGE_WIDTH_MM = 210.0
_MARGIN_MM = 15.0
_CONTENT_WIDTH_MM = _PAGE_WIDTH_MM - 2 * _MARGIN_MM


def _safe(text: str) -> str:
    """fpdf2's core Helvetica font only supports what its configured
    encoding maps to. cp1252 (set below) covers the bullet/dash/quote
    characters this app's masked IDs and copy actually use. The ₹ symbol
    isn't in cp1252 either — agent-generated reason strings (e.g.
    rule_agent's "Amount ₹342,829.13...") contain it verbatim, so it's
    rewritten to "Rs." to match how amounts are written everywhere else
    in this PDF, rather than falling through to the generic replacement
    below and rendering as a bare "?". Anything still outside cp1252
    after that is replaced rather than raising, since this renders
    arbitrary reason/evidence-summary text no one has pre-vetted for
    font support."""
    text = text.replace("₹", "Rs. ")
    return text.encode("cp1252", errors="replace").decode("cp1252")


class _CaseReportPDF(FPDF):
    """FPDF subclass carrying FraudLens's own header/footer and a few
    layout helpers — everything below is plain fpdf2, no exotic APIs."""

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.core_fonts_encoding = "cp1252"

    def header(self) -> None:
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(*_FOREGROUND)
        self.cell(0, 8, "FraudLens Investigation Report", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_draw_color(*_BORDER)
        self.set_line_width(0.3)
        self.line(_MARGIN_MM, 20, _PAGE_WIDTH_MM - _MARGIN_MM, 20)
        self.ln(6)

    def footer(self) -> None:
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*_MUTED)
        self.cell(
            0,
            10,
            f"Page {self.page_no()} - Generated by FraudLens. A qualified analyst must review "
            "the evidence before any action is taken.",
            align="C",
        )

    def section_title(self, title: str) -> None:
        self.ln(2)
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(*_COBALT)
        self.cell(0, 7, _safe(title.upper()), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_text_color(*_FOREGROUND)

    def field_row(self, label: str, value: str) -> None:
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*_MUTED)
        self.cell(48, 6, _safe(label), new_x=XPos.RIGHT, new_y=YPos.TOP)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*_FOREGROUND)
        self.multi_cell(0, 6, _safe(value), new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    def body_text(self, text: str) -> None:
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*_FOREGROUND)
        self.multi_cell(0, 5.5, _safe(text), new_x=XPos.LMARGIN, new_y=YPos.NEXT)


def build_case_report_pdf(case: FraudCase, analyst_decision: Optional[AnalystDecision] = None) -> bytes:
    """Lay out the full investigation report as a PDF and return its bytes."""
    engine_badge = _BADGES.get(case.decision.value, case.decision.value.upper())
    analyst_badge = (
        _BADGES.get(analyst_decision.decision, analyst_decision.decision.upper())
        if analyst_decision
        else "PENDING"
    )
    txn = case.transaction

    pdf = _CaseReportPDF(format="A4")
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.set_margins(_MARGIN_MM, _MARGIN_MM, _MARGIN_MM)
    pdf.add_page()

    pdf.field_row("Case ID:", case.case_id)
    pdf.field_row("Transaction ID:", case.txn_id)
    pdf.field_row("FraudLens recommendation:", engine_badge)
    pdf.field_row("Analyst decision:", analyst_badge)
    pdf.field_row("Report status:", "Draft")

    pdf.section_title("Transaction Summary")
    pdf.field_row("Account:", mask_identifier(txn.account_id))
    pdf.field_row("Amount:", f"Rs. {txn.amount:,.2f}")
    pdf.field_row("Merchant:", f"{mask_identifier(txn.merchant_id)} ({txn.merchant_category})")
    pdf.field_row("Timestamp:", txn.timestamp)
    pdf.field_row("Channel:", txn.channel)
    pdf.field_row("Device:", mask_identifier(txn.device_id))
    pdf.field_row("IP:", mask_ip(txn.ip_address))

    pdf.section_title("Risk Assessment")
    pdf.field_row("Risk score:", f"{case.final_score:.1%}")
    pdf.field_row("Model agreement confidence:", f"{case.confidence:.1%}")

    pdf.section_title("Agent Evidence")
    if case.agent_scores:
        with pdf.table(
            col_widths=(28, 16, 22, 34),
            text_align=("LEFT", "CENTER", "CENTER", "LEFT"),
        ) as table:
            header_row = table.row()
            for heading in ("Agent", "Score", "Confidence", "Key finding"):
                header_row.cell(heading)
            for a in case.agent_scores:
                row = table.row()
                row.cell(_safe(a.agent_name.replace("_", " ")))
                row.cell(f"{a.score:.2f}")
                row.cell(f"{a.confidence:.0%}")
                row.cell(_safe(a.reasons[0] if a.reasons else "-"))
    else:
        pdf.body_text("No agent evidence available for this case.")

    if case.graph_evidence:
        ge = case.graph_evidence
        pdf.section_title("Graph Evidence")
        pdf.field_row("Ring size:", str(ge.ring_size))
        pdf.field_row("Shared devices:", str(len(ge.shared_devices)))
        pdf.field_row("Shared IPs:", str(len(ge.shared_ips)))
        pdf.field_row("Suspicious cluster:", "Yes" if ge.suspicious_cluster else "No")
        if ge.evidence_summary:
            pdf.body_text(ge.evidence_summary)

    if case.fraud_dna_match:
        dna = case.fraud_dna_match
        pdf.section_title("Fraud DNA Match")
        pdf.field_row("Similarity:", f"{dna.similarity_score:.1%}")
        pdf.field_row("Matched pattern:", f"{dna.matched_ring_id} ({dna.fraud_type})")
        pdf.field_row("Modus operandi:", dna.modus_operandi)
        pdf.field_row("Recommendation:", dna.recommendation)

    pdf.section_title("Recommended Action")
    pdf.body_text(case.recommended_action)

    if analyst_decision:
        pdf.section_title("Analyst Decision")
        pdf.field_row("Decision:", analyst_badge)
        pdf.field_row("Analyst:", analyst_decision.analyst or "Unspecified")
        pdf.field_row("Notes:", analyst_decision.notes or "None provided.")

    output = pdf.output()
    return bytes(output)
